### ISSUE TITLE
BootUp

### ISSUE THREAD

**Issue by bararchy** [TheKernelCorp/NuummiteOS#10]
Awesome project ! really love the idea: 

![screenshot at 21-03-54](https://cloud.githubusercontent.com/assets/1631073/21582548/0059bfc2-d066-11e6-9293-c924d1cb1d68.png)

Is there a way to get basic shell (sh) to work ? 
Again, Awesome !! love it :)

**Comment by SplittyDev** [comment]
Hey, glad you like it!

At the moment we're focusing on the basics, which means that we're working on getting multitasking, proper exception handling, and all the fancy stuff.

As soon as we have a solid base system we'll be porting a C standard library to Nuummite, and we'll also get a shell going.

Sadly it's too early to give a good time estimate, so all we can say is that we're working on it.
If you want to talk to us directly, here's our [Discord][1] channel: https://discord.gg/nmESdX8

Feel free to ask follow-up questions here if you don't have Discord :)

[1]: https://discordapp.com/

**Comment by bararchy** [comment]
@SplittyDev Thanks for the invite and answer :)
