### ISSUE TITLE
Issue with Shift key

### ISSUE THREAD

**Issue by bararchy** [TheKernelCorp/NuummiteOS#30]
* Only the left shift key will allow special chars or Uppercase ASCII  
* Shift wont "stay pressed", and you need to press it again for each special char or uppercase

**Comment by SplittyDev** [comment]
@bararchy I just fixed this in b4d43b1,
Left shift now works correctly in QEMU, VMWare and Bochs.
Right shift works correctly in QEMU and VMWare.

Bochs still has some problems with right shift, it seems like it's sending the wrong key code.
I don't think that anything can be done to fix this. But maybe it works for you and my version of Bochs is just broken, who knows.

Please let me know if this works for you :)
