### ISSUE TITLE
Suggestion: a Canonical build-environment Docker image

### ISSUE THREAD

**Issue by anicholson** [TheKernelCorp/NuummiteOS#38]
That would  considerably shorten the barrier to entry for those  interested in having a play :)

**Comment by SplittyDev** [comment]
Hey, thanks for the suggestion!

Sadly, NuumiteOS isn't actively maintained right now (mainly due to a lack of time) and I personally don't have any experience with containerization.

If someone sent a PR our way we'd be very happy to merge it!

**Comment by anicholson** [comment]
@SplittyDev what's the situation over on FluoriteOS? Would it be welcome there?

**Comment by SplittyDev** [comment]
@anicholson FluoriteOS has a more stable base than NuummiteOS and should be the one that gets picked up again if anyone has time to work on it.

PRs are very welcome there, too :)
Having a docker image to build and run FluoriteOS in a reproducible fashion would be really great.
